project:
  type: website

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

website:
  favicon: hacker.png
  search: false
  twitter-card:
    creator: "@osanseviero"
  open-graph: true
  repo-actions: [issue]
  google-analytics: "G-SF72633X8L"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Misc Resources"
        href: resources.qmd
    right:
      - icon: twitter
        href: https://twitter.com/osanseviero
      - icon: linkedin
        href: https://www.linkedin.com/in/omarsanseviero/
      - icon: github
        href: https://github.com/osanseviero
      - icon: rss
        href: blog/index.xml      

metadata-files: [nbdev.yml]